#!/bin/bash
# This script recodes source lang files into XML Unicode.
# You should add your encodings to this file.  You need to have GNU Recode
# installed.
#
# It is important to:
# - fix the delimiters of php code: <?php and ?>
# - convert CRLF -> LF
# - remove all text before first <?php
# - remove all text after last ?>
# - convert "&apos;" -> "'"
# using 'convert.awk'

DESTDIR=./recoded

function prepare () {
	RET=""

	which recode >/dev/null 2>&1 || \
		RET="You must have GNU 'recode' installed to use this Makefile, but I could not find it in your path!\n"

	which sed >/dev/null 2>&1 || \
		RET="${RET}You must have sed installed to use this Makefile, but I could not find it in your path!\n"

	which awk >/dev/null 2>&1 || \
		RET="${RET}You must have awk installed to use this Makefile, but I could not find it in your path!\n"

	[ ! -z "$RET" ] && echo -ne $RET && exit 1
}

function rec () {
	for f in $@
	do
		[ ! -f $f ] && echo "$f is not a valid file." && continue
		DIRNAME=$(dirname $f)
		mkdir -p $DIRNAME
		echo "Recoding $f..."
		NAME=$(basename $f)
		cat $f | recode $(grep appcharset $f | cut -d"'" -f 4)..xml | ./convert.awk > $DIRNAME/$DESTDIR/$NAME
		chmod 644 $f $DIRNAME/$DESTDIR/$NAME
	done
}

function clean () {
	echo "Nuking recoded lang files..."
	for p in $@
	do
		rm -fv $p
	done
}

prepare

COMMAND=$1
[ -z "$COMMAND" ] && COMMAND="all"

case $COMMAND in
	all)
		# find all translation files in the source tree
		TARGETS=$(ls *.php | grep -v translations.php)
		rec $TARGETS
	;;
	clean)
		# find all recoded translation files in the source tree
		TARGETS=$(ls ${DESTDIR}/*.php | grep -v translations.php)
		clean $TARGETS
	;;
	*)
		rec $@
	;;
esac
